### ISSUE TITLE
These is a problem for the documentation of baseline

### ISSUE THREAD

**Issue by vcbeaut** [ymcui/cmrc2018#10]
If you use the data of CMRC 2018 (Simplified Chinese), the example of documentation of baseline will go wrong, because of inconsistent format between the data and standard format.

**Comment by ymcui** [comment]
The baseline codes are for `squad-like` version of CMRC 2018, as indicated in https://github.com/ymcui/cmrc2018/tree/master/baseline#datasets

**Comment by vcbeaut** [comment]
> The baseline codes are for `squad-like` version of CMRC 2018, as indicated in https://github.com/ymcui/cmrc2018/tree/master/baseline#datasets

the format between CMRC 2018 (Simplified Chinese) and DRCD (Traditional Chinese) is different, and DRCD (Traditional Chinese) is required and CMRC 2018 (Simplified Chinese) not, so the demo of Training don't normally work, because the demo used the data of CMRC 2018 (Simplified Chinese). you can check out, Thanks!

**Comment by vcbeaut** [comment]
ok, I found the squad-style-data, thanks!
