### ISSUE TITLE
请问为什么 File "cmrc2018_evaluate.py", line 33     if re.search(ur'[\u4e00-\u9fa5]', char) or char in sp_char:                                    ^ SyntaxError: invalid syntax会有这个报错啊

### ISSUE THREAD

**Issue by Mei0211** [ymcui/cmrc2018#19]

**Comment by Mei0211** [comment]
就是evaluate的时候的报错

**Comment by ymcui** [comment]
你用这个试一下： https://worksheets.codalab.org/bundles/0x28e4ab03d8cf4a31b1b82ed500385205

**Comment by Mei0211** [comment]
也会报错，想问问python cmrc2018_evaluate.py cmrc2018_dev.json predictions.json`这个的dev文件是data还是squad文件夹里的呢

**Comment by ymcui** [comment]
两种版本都支持。麻烦你把完整的错误信息贴出来。

**Comment by Mei0211** [comment]
~/cmrc2018/baseline$ python cmrc2018_evaluate.py /home/meishanxing/cmrc2018/squad-style-data/cmrc2018_dev.json /home/meishanxing/cmrc2018/output/dev_predictions.json
  File "cmrc2018_evaluate.py", line 33
    if re.search(ur'[\u4e00-\u9fa5]', char) or char in sp_char:
                                   ^
SyntaxError: invalid syntax

**Comment by ymcui** [comment]
不是，是运行给你新的链接里的脚本，你直接这里下载吧。
[cmrc2018_evaluate.py.zip](https://github.com/ymcui/cmrc2018/files/8569202/cmrc2018_evaluate.py.zip)
。

**Comment by Mei0211** [comment]
好的！ok了！！
感谢
