### ISSUE TITLE
更改过数据集结构的吗

### ISSUE THREAD

**Issue by policeme** [ymcui/cmrc2018#5]
在你的baseline代码里发现的数据集结构跟现有github上的目录结构完全不一样

**Comment by ymcui** [comment]
Baseline结构应该是用了SQuAD-style的数据集，codalab可以下载：https://worksheets.codalab.org/worksheets/0x92a80d2fab4b4f79a2b4064f7ddca9ce

**Comment by policeme** [comment]
dev是测试集吗 trail是挑战集吗

**Comment by ymcui** [comment]
dev：开发集
trial：试验集
test：测试集
challenge：挑战集

**Comment by ymcui** [comment]
测试集与挑战集不开放，仅接受提交系统后评测。具体方法请参考codalab页面。

**Comment by policeme** [comment]
好

**Comment by policeme** [comment]
可以提供下你们你们在Chinese-BERT-wwm训练cmrc2018的代码吗

**Comment by ymcui** [comment]
模型方面没有改动，数据格式你对的上基本就可以了。

**Comment by policeme** [comment]
好的
